---
highlighter: none
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
url: "https://docs.puppet.com"
safe: false
# YAML frontmatter defaults:
defaults: [ {scope: {path: ""},
             values: {layout: "default",
                      toc_levels: "23",
                      nav: "/_includes/fallback_nav.html"} } ]
defaultnav:
  /background/ssl: /_includes/background_ssl.html
  /security: /security/_security_toc.html
  /community: /_includes/community_nav.html
  /forge: /_includes/forge.html
  /guides/deployment_guide: /_includes/deploy_guide.html
  /guides/install_puppet: /_includes/puppet_general.html
  /de: /_includes/de_pe.html
  /es: /_includes/es_docs.html
  /es/hiera: /_includes/es_hiera1.html
  /es/learning: /_includes/es_learning_nav.html
  /es/pe/3.8: /_includes/es_pe38.html
  /ja: /_includes/ja_docs.html
  /ja/guides/install_puppet: /_includes/ja_puppet_general.html
  /ja/learning: /_includes/ja_learning_nav.html
  /ja/pe: /_includes/ja_docs.html
  /ja/puppet/3.7/reference: /_includes/ja_puppet_3_7.html
  /ja/puppet/4.2/reference: /_includes/ja_puppet4.2.html
  /learning: /_includes/learning_nav.html
  /mcollective: /_includes/mcollective_menu.html
  /mcollective1.2: /_includes/mcollective_1.2.html
  /upgrade: /upgrade/_upgrade_toc.html

#Anatomy of an external source:
#  /puppetdb/2.2:                                   # The absolute URL where the source's contents should be mounted in the final site.
#    repo: git://github.com/puppetlabs/puppetdb.git # The URL of the upstream repo, in any form `git clone` understands. This must be accessible to anyone who will need to build the site.
#    commit: origin/2.2.x                           # A git treeish (in any form `git checkout` understands) that the external source should track. This should almost always be either a tag, which will never update, or an upstream tracking branch on the default "origin" remote (origin/<branch>), which will update every time someone builds the site.
#    subdirectory: documentation                    # A subdirectory within the remote repository that contains the documentation files that we'll build and mount at the specified url.
externalsources:
  /mcollective:
    repo: git://github.com/puppetlabs/marionette-collective.git
    commit: origin/master
    subdirectory: website
  /mcollective1.2:
    repo: git://github.com/nfagerlund/marionette-collective.git
    commit: origin/docs_1.2
    subdirectory: website


symlink_latest:
  - puppet
  - puppetdb
  - puppetserver
  - hiera
  - facter
  - pe
lock_latest:
 # puppet: 4.4
 # hiera: 3.1

document_names:
  pe: Puppet Enterprise
  puppet: Puppet
  puppetserver: Puppet Server
  puppetdb: PuppetDB
  hiera: Hiera
  facter: Facter

# Anatomy of a document:
#  /pe/2015.3:                    # Base URL for this doc, starting from the root of the site.
#    doc: pe                      # Which document group it's a part of. Used to determine this doc's siblings.
#    version: 2015.3              # Version. Used for associating confirmed version numbers with a URL.
#    nav: ./_pe_toc.html          # Nav snippet. Can be an absolute URL, or relative to the base URL.
#    hide: false                  # Whether to hide this version in the version switcher. Optional; defaults to false.
#    draft: false                 # Whether to warn in the version note that this is a draft for an unreleased version. Optional; defaults to false.
#    external_source:             # External source. (Works the same as external sources above.) Optional; if absent, we use content from this repo instead of an external repo.
#      repo: git@github.com:puppetlabs/pe-docs-private.git   # A git repo
#      commit: origin/pe2015.3.1
#      subdirectory: source
#    my_versions:                 # A hash, where you can specify the most-relevant version for any number of other documents.
#      puppet: 4.3                # The keys of this hash should be document group IDs; that is, the value of the `doc` key from another document.
#      facter: 3.1
#      hiera: 3.0
#      puppetserver: 2.2
#      puppetdb: 3.2
documents:
  /pe/2016.2:
    doc: pe
    version: 2016.2
    nav: ./_pe_toc.html
    external_source:
      repo: git@github.com:puppetlabs/pe-docs-private.git
      commit: origin/pe2016.2.1
      subdirectory: source
    my_versions:
      puppet: 4.5
      facter: 3.1
      hiera: 3.2
      puppetserver: 2.4
      puppetdb: 4.1

  /pe/2016.1:
    doc: pe
    version: 2016.1
    nav: ./_pe_toc.html
    external_source:
      repo: git@github.com:puppetlabs/pe-docs-private.git
      commit: origin/pe2016.1.2
      subdirectory: source
    my_versions:
      puppet: 4.4
      facter: 3.1
      hiera: 3.1
      puppetserver: 2.3
      puppetdb: 4.0

  /pe/2015.3:
    doc: pe
    version: 2015.3
    nav: ./_pe_toc.html
    external_source:
      repo: git@github.com:puppetlabs/pe-docs-private.git
      commit: origin/pe2015.3.3
      subdirectory: source
    my_versions:
      puppet: 4.3
      facter: 3.1
      hiera: 3.0
      puppetserver: 2.2
      puppetdb: 3.2
  /pe/2015.2:
    doc: pe
    version: 2015.2
    nav: ./_pe_toc.html
    external_source:
      repo: git@github.com:puppetlabs/pe-docs-private.git
      commit: origin/pe2015.2.3
      subdirectory: source
    my_versions:
      puppet: 4.2
      facter: 3.1
      hiera: 3.0
      puppetserver: 2.1
      puppetdb: 3.1
  /pe/3.8:
    doc: pe
    version: 3.8
    nav: ./_pe_toc.html
    external_source:
      repo: git@github.com:puppetlabs/pe-docs-private.git
      commit: origin/pe3.8.6
      subdirectory: source
    my_versions:
      puppet: 3.8
      facter: 2.4
      hiera: 1
      puppetserver: 1.1
      puppetdb: 2.3
  /pe/3.7:
    doc: pe
    version: 3.7
    nav: ./_pe_toc.html
    external_source:
      repo: git@github.com:puppetlabs/pe-docs-private.git
      commit: origin/pe3.7
      subdirectory: source
    my_versions:
      puppet: 3.7
      facter: 2.3
      hiera: 1
      puppetserver: 1.0
      puppetdb: 2.2
  /pe/3.3:
    doc: pe
    version: 3.3
    nav: /_includes/pe33.html
    my_versions:
      puppet: 3.6
      facter: 1.7
      hiera: 1
      puppetdb: 1.6
  /pe/3.2:
    doc: pe
    version: 3.2
    nav: /_includes/pe32.html
    my_versions:
      puppet: 3
      facter: 1.7
      hiera: 1
      puppetdb: 1.5
  /pe/3.1:
    doc: pe
    version: 3.1
    nav: /_includes/pe31.html
  /pe/3.0:
    doc: pe
    version: 3.0
    nav: /_includes/pe30.html
  /pe/2.8:
    doc: pe
    version: 2.8
    nav: /_includes/pe28.html
    hide: true
  /pe/2.7:
    doc: pe
    version: 2.7
    nav: /_includes/pe27.html
    hide: true
  /pe/2.6:
    doc: pe
    version: 2.6
    nav: /_includes/pe26.html
    hide: true
  /pe/2.5:
    doc: pe
    version: 2.5
    nav: /_includes/pe25.html
    hide: true
  /pe/2.0:
    doc: pe
    version: 2.0
    nav: /_includes/pe_2.0_nav.markdown
    hide: true

  /puppet/4.7/reference:
    doc: puppet
    version: 4.7
    nav: ./_puppet_toc.html
    my_versions:
      facter: 3.4
      hiera: 3.2
      puppetserver: 2.6
  /puppet/4.6/reference:
    doc: puppet
    version: 4.6
    nav: ./_puppet_toc.html
    my_versions:
      facter: 3.4
      hiera: 3.2
      puppetserver: 2.6
  /puppet/4.5/reference:
    doc: puppet
    version: 4.5
    nav: ./_puppet_toc.html
    my_versions:
      facter: 3.3
      hiera: 3.2
      puppetserver: 2.4
  /puppet/4.4/reference:
    doc: puppet
    version: 4.4
    nav: ./_puppet_toc.html
    my_versions:
      facter: 3.1
      hiera: 3.1
      puppetserver: 2.3
  /puppet/4.3/reference:
    doc: puppet
    version: 4.3
    nav: ./_puppet_toc.html
    my_versions:
      facter: 3.1
      hiera: 3.0
      puppetserver: 2.2
  /puppet/4.2/reference:
    doc: puppet
    version: 4.2
    nav: /_includes/puppet4.2.html
    my_versions:
      facter: 3.1
      hiera: 3.0
      puppetserver: 2.1
  /puppet/4.1/reference:
    doc: puppet
    version: 4.1
    nav: /_includes/puppet4.1.html
    my_versions:
      facter: 2.4
      hiera: 2.0
      puppetserver: 2.1
  /puppet/4.0/reference:
    doc: puppet
    version: 4.0
    nav: /_includes/puppet_4.html
  /puppet/3.8/reference:
    doc: puppet
    version: 3.8
    nav: /_includes/puppet_3_8.html
    my_versions:
      facter: 2.4
      hiera: 1
      puppetserver: 1.1
  /puppet/3.7/reference:
    doc: puppet
    version: 3.7
    nav: /_includes/puppet_3_7.html
  /puppet/3.6/reference:
    doc: puppet
    version: 3.6
    nav: /_includes/puppet_3_6.html
  /puppet/3.5/reference:
    doc: puppet
    version: 3.5
    nav: /_includes/puppet_3_5.html
  /puppet/3/reference:
    doc: puppet
    version: 3
    nav: /_includes/puppet_3.html
    hide: true
  /puppet/2.7/reference:
    doc: puppet
    version: 2.7
    nav: /_includes/puppet_2_7.html
    hide: true
  /puppet/2.6/reference:
    doc: puppet
    version: 2.6
    nav: /_includes/puppet_2_6.html
    hide: true
  /puppet/0.25/reference:
    doc: puppet
    version: 0.25
    nav: /_includes/puppet_0_25.html
    hide: true
  /puppet/0.24/reference:
    doc: puppet
    version: 0.24
    nav: /_includes/puppet_0_24.html
    hide: true

  /facter/3.4:
    doc: facter
    version: 3.4
    nav: ./_facter_toc.html
  /facter/3.3:
    doc: facter
    version: 3.3
    nav: ./_facter_toc.html
  /facter/3.1:
    doc: facter
    version: 3.1
    nav: ./_facter_toc.html
  /facter/3.0:
    doc: facter
    version: 3.0
    nav: ./_facter_toc.html
  /facter/2.4:
    doc: facter
    version: 2.4
    nav: /_includes/facter24.html
  /facter/2.3:
    doc: facter
    version: 2.3
    nav: /_includes/facter23.html
  /facter/2.2:
    doc: facter
    version: 2.2
    nav: /_includes/facter22.html
  /facter/2.1:
    doc: facter
    version: 2.1
    nav: /_includes/facter21.html
  /facter/2.0:
    doc: facter
    version: 2.0
    nav: /_includes/facter20.html
  /facter/1.7:
    doc: facter
    version: 1.7
    nav: /_includes/facter17.html
  /facter/1.6:
    doc: facter
    version: 1.6
    nav: /_includes/facter16.html

  /hiera/3.2:
    doc: hiera
    version: 3.2
    nav: ./_hiera_toc.html
  /hiera/3.1:
    doc: hiera
    version: 3.1
    nav: ./_hiera_toc.html
  /hiera/3.0:
    doc: hiera
    version: 3.0
    nav: /_includes/hiera30.html
  /hiera/2.0:
    doc: hiera
    version: 2.0
    nav: /_includes/hiera20.html
  /hiera/1:
    doc: hiera
    version: 1
    nav: /_includes/hiera1.html

  /puppetserver/2.6:
    doc: puppetserver
    version: 2.6
    nav: /puppet/4.6/reference/_puppet_toc.html
    external_source:
      repo: git://github.com/puppetlabs/puppetserver.git
      commit: 16bf802ed19e58ac5362aeee72c9ed0fb917dae9
      subdirectory: documentation
    my_versions:
      puppet: 4.6
      facter: 3.3
      hiera: 3.2
  /puppetserver/2.5:
    doc: puppetserver
    version: 2.5
    nav: /puppet/4.6/reference/_puppet_toc.html
    external_source:
      repo: git://github.com/puppetlabs/puppetserver.git
      commit: ba86848
      subdirectory: documentation
    my_versions:
      puppet: 4.6
      facter: 3.3
      hiera: 3.2
  /puppetserver/2.4:
    doc: puppetserver
    version: 2.4
    nav: /puppet/4.5/reference/_puppet_toc.html
    external_source:
      repo: git://github.com/puppetlabs/puppetserver.git
      commit: 522083d
      subdirectory: documentation
    my_versions:
      puppet: 4.5
      facter: 3.1
      hiera: 3.2
  /puppetserver/2.3:
    doc: puppetserver
    version: 2.3
    nav: /puppet/4.4/reference/_puppet_toc.html
    external_source:
      repo: git://github.com/puppetlabs/puppetserver.git
      commit: 585c701
      subdirectory: documentation
    my_versions:
      puppet: 4.4
      facter: 3.1
      hiera: 3.1
  /puppetserver/2.2:
    doc: puppetserver
    version: 2.2
    nav: /puppet/4.3/reference/_puppet_toc.html
    external_source:
      repo: git://github.com/puppetlabs/puppetserver.git
      commit: puppet-server-2.2.1
      subdirectory: documentation
    my_versions:
      puppet: 4.3
      facter: 3.1
      hiera: 3.0
  /puppetserver/2.1:
    doc: puppetserver
    version: 2.1
    nav: /_includes/puppet4.2.html
    external_source:
      repo: git://github.com/puppetlabs/puppetserver.git
      # This is a tag:
      commit: puppet-server-2.1.3-alpha1
      subdirectory: documentation
  /puppetserver/2.0:
    doc: puppetserver
    version: 2.0
    nav: /_includes/server2.0.html
    external_source:
      repo: git://github.com/puppetlabs/puppetserver.git
      commit: 239776a
      subdirectory: documentation
  /puppetserver/1.2:
    doc: puppetserver
    version: 1.2
    nav: /_includes/puppet_3_8.html
    external_source:
      repo: git://github.com/puppetlabs/puppetserver.git
      commit: origin/1.x
      subdirectory: documentation
  /puppetserver/1.1:
    doc: puppetserver
    version: 1.1
    nav: /_includes/puppet_3_8.html
    external_source:
      repo: git://github.com/puppetlabs/puppetserver.git
      commit: bbc73f6da0a17eac4fbf84758b477ec9dd4cebb2
      subdirectory: documentation
  /puppetserver/1.0:
    doc: puppetserver
    version: 1.0
    nav: /_includes/server1.0.html
    external_source:
      repo: git://github.com/puppetlabs/puppetserver.git
      commit: ce030bb
      subdirectory: documentation

  /puppetdb/4.2:
    doc: puppetdb
    version: 4.2
    nav: ./_puppetdb_nav.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/stable
      subdirectory: documentation
  /puppetdb/4.1:
    doc: puppetdb
    version: 4.1
    nav: ./_puppetdb_nav.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/4.1.x
      subdirectory: documentation
  /puppetdb/4.0:
    doc: puppetdb
    version: 4.0
    nav: ./_puppetdb_nav.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/4.0.x
      subdirectory: documentation
  /puppetdb/3.2:
    doc: puppetdb
    version: 3.2
    nav: ./_puppetdb_nav.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/3.2.x
      subdirectory: documentation
  /puppetdb/3.1:
    doc: puppetdb
    version: 3.1
    nav: ./_puppetdb_nav.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/3.1.x
      subdirectory: documentation
  /puppetdb/3.0:
    doc: puppetdb
    version: 3.0
    nav: ./_puppetdb_nav.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/3.0.x
      subdirectory: documentation
  /puppetdb/2.3:
    doc: puppetdb
    version: 2.3
    nav: ./_puppetdb_nav.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/2.3.x
      subdirectory: documentation
  /puppetdb/2.2:
    doc: puppetdb
    version: 2.2
    nav: /_includes/puppetdb2.2.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/2.2.x
      subdirectory: documentation
  /puppetdb/2.1:
    doc: puppetdb
    version: 2.1
    nav: /_includes/puppetdb2.1.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/2.1.x
      subdirectory: documentation
  /puppetdb/2.0:
    doc: puppetdb
    version: 2.0
    nav: /_includes/puppetdb2.0.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/2.0.x
      subdirectory: documentation
  /puppetdb/1.6:
    doc: puppetdb
    version: 1.6
    nav: /_includes/puppetdb1.6.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/1.6.x
      subdirectory: documentation
  /puppetdb/1.5:
    doc: puppetdb
    version: 1.5
    nav: /_includes/puppetdb1.5.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: 1.5.x-docs
      subdirectory: documentation
  /puppetdb/1.4:
    doc: puppetdb
    version: 1.4
    nav: /_includes/puppetdb1.4.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: 1.4.x-docs
      subdirectory: documentation
  /puppetdb/1.3:
    doc: puppetdb
    version: 1.3
    nav: /_includes/puppetdb1.3.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: 1.3.x-docs
      subdirectory: documentation
  /puppetdb/1.2:
    doc: puppetdb
    version: 1.2
    nav: /_includes/puppetdb1.2.html
    hide: true
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: 1.2.x-docs
      subdirectory: documentation
  /puppetdb/1.1:
    doc: puppetdb
    version: 1.1
    nav: /_includes/puppetdb1.1.html
    hide: true
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: 1.1.x-docs
      subdirectory: documentation
  /puppetdb/1:
    doc: puppetdb
    version: 1
    nav: /_includes/puppetdb1.html
    hide: true
  /puppetdb/0.9:
    doc: puppetdb
    version: 0.9
    nav: /_includes/puppetdb0.9.html
    hide: true
  /puppetdb/master:
    doc: puppetdb
    version: master
    nav: ./_puppetdb_nav.html
    external_source:
      repo: git://github.com/puppetlabs/puppetdb.git
      commit: origin/master
      subdirectory: documentation



---
